	db "Note@"
	db "Note@"
	db "Brightpowder@"
	db "Note@"
	db "Note@"
	db "Teru-sama@"
	db "Armour@"
	db "Moon stone@"
	db "Antidote@"
	db "Burn heal@"
	db "Ice heal@"
	db "Awakening@"
	db "Parlyz heal@"
	db "Bones@"
	db "#rus gel@"
	db "Hyper potion@"
	db "Super potion@"
	db "Potion@"
	db "Escape rope@"
	db "Repel@"
	db "Max elixer@"
	db "Fire stone@"
	db "Thunderstone@"
	db "Water stone@"
	db "Teru-sama@"
	db "Hp up@"
	db "Protein@"
	db "Iron@"
	db "Carbos@"
	db "Lucky punch@"
	db "Calcium@"
	db "# orb@"
	db "X accuracy@"
	db "Leaf stone@"
	db "Metal powder@"
	db "Nugget@"
	db "# doll@"
	db "Skull@"
	db "Revive@"
	db "Max revive@"
	db "Guard spec.@"
	db "Super repel@"
	db "Max repel@"
	db "Dire hit@"
	db "Teru-sama@"
	db "Fresh water@"
	db "Soda pop@"
	db "Lemonade@"
	db "X attack@"
	db "Teru-sama@"
	db "X defend@"
	db "X speed@"
	db "X special@"
	db "Coin case@"
	db "Itemfinder@"
	db "Teru-sama@"
	db "Exp.share@"
	db "Old rod@"
	db "Good rod@"
	db "Silver leaf@"
	db "Super rod@"
	db "Pp up@"
	db "Ether@"
	db "Max ether@"
	db "Elixer@"
	db "Red scale@"
	db "Gem@" ; secret potion
	db "S.s.ticket@"
	db "Mystery egg@"
	db "Clear bell@"
	db "Silver wing@"
	db "Moomoo milk@"
	db "Quick claw@"
	db "Psncureberry@"
	db "Gold leaf@"
	db "Soft sand@"
	db "Sharp beak@"
	db "Przcureberry@"
	db "Burnt berry@"
	db "Ice berry@"
	db "Poison barb@"
	db "King's rock@"
	db "Bitter berry@"
	db "Mint berry@"
	db "Red apricorn@"
	db "Tinymushroom@"
	db "Big mushroom@"
	db "Silverpowder@"
	db "Blu apricorn@"
	db "Teru-sama@"
	db "Amulet coin@"
	db "Ylw apricorn@"
	db "Grn apricorn@"
	db "Cleanse tag@"
	db "Mystic water@"
	db "Twistedspoon@"
	db "Wht apricorn@"
	db "Blackbelt@"
	db "Blk apricorn@"
	db "Teru-sama@"
	db "Pnk apricorn@"
	db "Blackglasses@"
	db "Slowpoketail@"
	db "Pink bow@"
	db "Magic Scarf@"
	db "Smoke ball@"
	db "Nevermeltice@"
	db "Magnet@"
	db "Miracleberry@"
	db "Pearl@"
	db "Big pearl@"
	db "Everstone@"
	db "Spell tag@"
	db "Ragecandybar@"
	db "Gs ball@"
	db "Gem@" ; blue card
	db "Miracle seed@"
	db "Thick club@"
	db "Focus band@"
	db "Teru-sama@"
	db "Energypowder@"
	db "Energy root@"
	db "Heal powder@"
	db "Revival herb@"
	db "Hard stone@"
	db "Lucky egg@"
	db "Rock hammer@" ; card key
	db "Machine part@"
	db "Egg ticket@"
	db "Lost item@"
	db "Stardust@"
	db "Star piece@"
	db "Gem@" ; basement key
	db "Pass@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Charcoal@"
	db "Berry juice@"
	db "Scope lens@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Metal coat@"
	db "Dragon fang@"
	db "Teru-sama@"
	db "Leftovers@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Mysteryberry@"
	db "Dragon scale@"
	db "Berserk gene@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Sacred ash@"
	db "Heavy ball@"
	db "Flower mail@"
	db "Level ball@"
	db "Lure ball@"
	db "# bits@"
	db "Teru-sama@"
	db "Light ball@"
	db "Friend ball@"
	db "Moon ball@"
	db "Love ball@"
	db "Normal box@"
	db "Gorgeous box@"
	db "Sun stone@"
	db "Polkadot bow@"
	db "Teru-sama@"
	db "Up-grade@"
	db "Berry@"
	db "Gold berry@"
	db "Squirtbottle@"
	db "Teru-sama@"
	db "Super Rock@"
	db "Devo-stone@"
	db "Teru-sama@"
	db "Brick piece@"
	db "Surf mail@"
	db "Litebluemail@"
	db "Portraitmail@"
	db "Lovely mail@"
	db "Eon mail@"
	db "Morph mail@"
	db "Bluesky mail@"
	db "Music mail@"
	db "Mirage mail@"
	db "Teru-sama@"
	db "Tm01@"
	db "Tm02@"
	db "Tm03@"
	db "Tm04@"
	db "Teru-sama@"
	db "Tm05@"
	db "Tm06@"
	db "Tm07@"
	db "Tm08@"
	db "Tm09@"
	db "Tm10@"
	db "Tm11@"
	db "Tm12@"
	db "Tm13@"
	db "Tm14@"
	db "Tm15@"
	db "Tm16@"
	db "Tm17@"
	db "Tm18@"
	db "Tm19@"
	db "Tm20@"
	db "Tm21@"
	db "Tm22@"
	db "Tm23@"
	db "Tm24@"
	db "Tm25@"
	db "Tm26@"
	db "Tm27@"
	db "Tm28@"
	db "Teru-sama@"
	db "Tm29@"
	db "Tm30@"
	db "Tm31@"
	db "Tm32@"
	db "Tm33@"
	db "Tm34@"
	db "Tm35@"
	db "Tm36@"
	db "Tm37@"
	db "Tm38@"
	db "Tm39@"
	db "Tm40@"
	db "Tm41@"
	db "Tm42@"
	db "Tm43@"
	db "Tm44@"
	db "Tm45@"
	db "Tm46@"
	db "Tm47@"
	db "Tm48@"
	db "Tm49@"
	db "Tm50@"
	db "Hm01@"
	db "Hm02@"
	db "Hm03@"
	db "Hm04@"
	db "Hm05@"
	db "Hm06@"
	db "Hm07@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "?@"

; gem count = 3