	db "Pound@"
	db "Karate chop@"
	db "Doubleslap@"
	db "Comet punch@"
	db "Mega punch@"
	db "Pay day@"
	db "Fire punch@"
	db "Ice punch@"
	db "Thunderpunch@"
	db "Scratch@"
	db "Vicegrip@"
	db "Guillotine@"
	db "Razor wind@"
	db "Swords dance@"
	db "Cut@"
	db "Gust@"
	db "Wing attack@"
	db "Whirlwind@"
	db "Fly@"
	db "Bind@"
	db "Slam@"
	db "Vine whip@"
	db "Stomp@"
	db "Double kick@"
	db "Mega kick@"
	db "Jump kick@"
	db "Rolling kick@"
	db "Sand-attack@"
	db "Headbutt@"
	db "Horn attack@"
	db "Fury attack@"
	db "Horn drill@"
	db "Tackle@"
	db "Body slam@"
	db "Wrap@"
	db "Take down@"
	db "Thrash@"
	db "Double-edge@"
	db "Tail whip@"
	db "Poison sting@"
	db "Twineedle@"
	db "Pin missile@"
	db "Leer@"
	db "Bite@"
	db "Growl@"
	db "Roar@"
	db "Sing@"
	db "Supersonic@"
	db "Sonicboom@"
	db "Disable@"
	db "Acid@"
	db "Ember@"
	db "Flamethrower@"
	db "Mist@"
	db "Water gun@"
	db "Hydro pump@"
	db "Surf@"
	db "Ice beam@"
	db "Blizzard@"
	db "Psybeam@"
	db "Bubblebeam@"
	db "Aurora beam@"
	db "Hyper beam@"
	db "Peck@"
	db "Drill peck@"
	db "Submission@"
	db "Low kick@"
	db "Counter@"
	db "Seismic toss@"
	db "Strength@"
	db "Absorb@"
	db "Mega drain@"
	db "Leech seed@"
	db "Growth@"
	db "Razor leaf@"
	db "Solarbeam@"
	db "Poisonpowder@"
	db "Stun spore@"
	db "Sleep powder@"
	db "Petal dance@"
	db "String shot@"
	db "Dragon rage@"
	db "Fire spin@"
	db "Thundershock@"
	db "Thunderbolt@"
	db "Thunder wave@"
	db "Thunder@"
	db "Rock throw@"
	db "Earthquake@"
	db "Fissure@"
	db "Dig@"
	db "Toxic@"
	db "Confusion@"
	db "Psychic@"
	db "Hypnosis@"
	db "Meditate@"
	db "Agility@"
	db "Quick attack@"
	db "Rage@"
	db "Teleport@"
	db "Night shade@"
	db "Mimic@"
	db "Screech@"
	db "Double team@"
	db "Recover@"
	db "Harden@"
	db "Minimize@"
	db "Smokescreen@"
	db "Confuse ray@"
	db "Withdraw@"
	db "Defense curl@"
	db "Barrier@"
	db "Light screen@"
	db "Haze@"
	db "Reflect@"
	db "Focus energy@"
	db "Bide@"
	db "Metronome@"
	db "Mirror move@"
	db "Selfdestruct@"
	db "Egg bomb@"
	db "Lick@"
	db "Smog@"
	db "Sludge@"
	db "Bone club@"
	db "Fire blast@"
	db "Waterfall@"
	db "Clamp@"
	db "Swift@"
	db "Skull bash@"
	db "Spike cannon@"
	db "Constrict@"
	db "Amnesia@"
	db "Kinesis@"
	db "Softboiled@"
	db "Hi jump kick@"
	db "Glare@"
	db "Dream eater@"
	db "Poison gas@"
	db "Barrage@"
	db "Leech life@"
	db "Lovely kiss@"
	db "Sky attack@"
	db "Transform@"
	db "Bubble@"
	db "Dizzy punch@"
	db "Spore@"
	db "Flash@"
	db "Psywave@"
	db "Splash@"
	db "Acid armor@"
	db "Crabhammer@"
	db "Explosion@"
	db "Fury swipes@"
	db "Bonemerang@"
	db "Rest@"
	db "Rock slide@"
	db "Hyper fang@"
	db "Sharpen@"
	db "Conversion@"
	db "Tri attack@"
	db "Super fang@"
	db "Slash@"
	db "Substitute@"
	db "Struggle@"
	db "Sketch@"
	db "Triple kick@"
	db "Thief@"
	db "Spider web@"
	db "Mind reader@"
	db "Nightmare@"
	db "Flame wheel@"
	db "Snore@"
	db "Curse@"
	db "Flail@"
	db "Conversion2@"
	db "Aeroblast@"
	db "Cotton spore@"
	db "Reversal@"
	db "Spite@"
	db "Powder snow@"
	db "Protect@"
	db "Mach punch@"
	db "Scary face@"
	db "Faint attack@"
	db "Sweet kiss@"
	db "Belly drum@"
	db "Sludge bomb@"
	db "Mud-slap@"
	db "Octazooka@"
	db "Spikes@"
	db "Zap cannon@"
	db "Foresight@"
	db "Destiny bond@"
	db "Perish song@"
	db "Icy wind@"
	db "Detect@"
	db "Bone rush@"
	db "Lock-on@"
	db "Outrage@"
	db "Sandstorm@"
	db "Giga drain@"
	db "Endure@"
	db "Charm@"
	db "Rollout@"
	db "False swipe@"
	db "Swagger@"
	db "Milk drink@"
	db "Spark@"
	db "Fury cutter@"
	db "Steel wing@"
	db "Mean look@"
	db "Attract@"
	db "Sleep talk@"
	db "Heal bell@"
	db "Return@"
	db "Present@"
	db "Frustration@"
	db "Safeguard@"
	db "Pain split@"
	db "Sacred fire@"
	db "Magnitude@"
	db "Dynamicpunch@"
	db "Megahorn@"
	db "Dragonbreath@"
	db "Baton pass@"
	db "Encore@"
	db "Pursuit@"
	db "Rapid spin@"
	db "Sweet scent@"
	db "Iron tail@"
	db "Metal claw@"
	db "Vital throw@"
	db "Morning sun@"
	db "Synthesis@"
	db "Moonlight@"
	db "Hidden power@"
	db "Cross chop@"
	db "Twister@"
	db "Rain dance@"
	db "Sunny day@"
	db "Crunch@"
	db "Mirror coat@"
	db "Psych up@"
	db "Extremespeed@"
	db "Ancientpower@"
	db "Shadow ball@"
	db "Future sight@"
	db "Rock smash@"
	db "Whirlpool@"
	db "Beat up@"
